# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78819882be70594b4f6e74c080afff18ec04797d22cae50a319c9dd667cce6750beffafec17331c745653e787a924a334306d53895f60ad3f5163958229a677b

test:
  secret_key_base: d9f17189b7fdd8a2717a89dbb49cd83e7774b12774aea00f728237d5f2dc5c8cfbcc66b82f584071da6bcaa64f09ee03fb0e729c8162ad8b939f0ec7dc7f9ccf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
